### ISSUE TITLE
Installing nodegit fails

### ISSUE THREAD

**Issue by SwiftPengu** [kimmobrunfeldt/git-hours#11]
I couldn't manage to run the program after building. So, I tried the Vagrant method.
This resulted in some build errors for nodegit, I have attached a log below:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'precise64'...

[KProgress: 60%
[KProgress: 90%
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: git-hours_default_1443006363068_89836
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 5.0
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/SwiftPengu/Documents/git-hours
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Ign http://us.archive.ubuntu.com precise InRelease
==> default: Ign http://us.archive.ubuntu.com precise-updates InRelease
==> default: Ign http://us.archive.ubuntu.com precise-backports InRelease
==> default: Hit http://us.archive.ubuntu.com precise Release.gpg
==> default: Get:1 http://us.archive.ubuntu.com precise-updates Release.gpg [198 B]
==> default: Get:2 http://us.archive.ubuntu.com precise-backports Release.gpg [198 B]
==> default: Hit http://us.archive.ubuntu.com precise Release
==> default: Get:3 http://us.archive.ubuntu.com precise-updates Release [196 kB]
==> default: Get:4 http://us.archive.ubuntu.com precise-backports Release [54.3 kB]
==> default: Ign http://security.ubuntu.com precise-security InRelease
==> default: Get:5 http://security.ubuntu.com precise-security Release.gpg [198 B]
==> default: Get:6 http://security.ubuntu.com precise-security Release [54.3 kB]
==> default: Hit http://us.archive.ubuntu.com precise/main Sources
==> default: Hit http://us.archive.ubuntu.com precise/restricted Sources
==> default: Hit http://us.archive.ubuntu.com precise/universe Sources
==> default: Hit http://us.archive.ubuntu.com precise/multiverse Sources
==> default: Hit http://us.archive.ubuntu.com precise/main amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise/restricted amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise/universe amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise/multiverse amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise/main i386 Packages
==> default: Get:7 http://security.ubuntu.com precise-security/main Sources [134 kB]
==> default: Hit http://us.archive.ubuntu.com precise/restricted i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise/universe i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise/multiverse i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise/main TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise/multiverse TranslationIndex
==> default: Get:8 http://security.ubuntu.com precise-security/restricted Sources [3,759 B]
==> default: Get:9 http://security.ubuntu.com precise-security/universe Sources [43.9 kB]
==> default: Get:10 http://security.ubuntu.com precise-security/multiverse Sources [2,199 B]
==> default: Get:11 http://security.ubuntu.com precise-security/main amd64 Packages [544 kB]
==> default: Hit http://us.archive.ubuntu.com precise/restricted TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise/universe TranslationIndex
==> default: Get:12 http://us.archive.ubuntu.com precise-updates/main Sources [492 kB]
==> default: Get:13 http://security.ubuntu.com precise-security/restricted amd64 Packages [8,943 B]
==> default: Get:14 http://security.ubuntu.com precise-security/universe amd64 Packages [124 kB]
==> default: Get:15 http://security.ubuntu.com precise-security/multiverse amd64 Packages [2,695 B]
==> default: Get:16 http://security.ubuntu.com precise-security/main i386 Packages [598 kB]
==> default: Get:17 http://security.ubuntu.com precise-security/restricted i386 Packages [8,939 B]
==> default: Get:18 http://security.ubuntu.com precise-security/universe i386 Packages [132 kB]
==> default: Get:19 http://security.ubuntu.com precise-security/multiverse i386 Packages [2,872 B]
==> default: Get:20 http://security.ubuntu.com precise-security/main TranslationIndex [208 B]
==> default: Get:21 http://security.ubuntu.com precise-security/multiverse TranslationIndex [199 B]
==> default: Get:22 http://security.ubuntu.com precise-security/restricted TranslationIndex [202 B]
==> default: Get:23 http://security.ubuntu.com precise-security/universe TranslationIndex [205 B]
==> default: Get:24 http://security.ubuntu.com precise-security/main Translation-en [239 kB]
==> default: Get:25 http://security.ubuntu.com precise-security/multiverse Translation-en [1,408 B]
==> default: Get:26 http://security.ubuntu.com precise-security/restricted Translation-en [2,066 B]
==> default: Get:27 http://security.ubuntu.com precise-security/universe Translation-en [78.0 kB]
==> default: Get:28 http://us.archive.ubuntu.com precise-updates/restricted Sources [8,024 B]
==> default: Get:29 http://us.archive.ubuntu.com precise-updates/universe Sources [122 kB]
==> default: Get:30 http://us.archive.ubuntu.com precise-updates/multiverse Sources [9,733 B]
==> default: Get:31 http://us.archive.ubuntu.com precise-updates/main amd64 Packages [933 kB]
==> default: Get:32 http://us.archive.ubuntu.com precise-updates/restricted amd64 Packages [13.7 kB]
==> default: Get:33 http://us.archive.ubuntu.com precise-updates/universe amd64 Packages [269 kB]
==> default: Get:34 http://us.archive.ubuntu.com precise-updates/multiverse amd64 Packages [16.5 kB]
==> default: Get:35 http://us.archive.ubuntu.com precise-updates/main i386 Packages [984 kB]
==> default: Get:36 http://us.archive.ubuntu.com precise-updates/restricted i386 Packages [13.6 kB]
==> default: Get:37 http://us.archive.ubuntu.com precise-updates/universe i386 Packages [278 kB]
==> default: Get:38 http://us.archive.ubuntu.com precise-updates/multiverse i386 Packages [16.7 kB]
==> default: Get:39 http://us.archive.ubuntu.com precise-updates/main TranslationIndex [10.6 kB]
==> default: Get:40 http://us.archive.ubuntu.com precise-updates/multiverse TranslationIndex [7,613 B]
==> default: Get:41 http://us.archive.ubuntu.com precise-updates/restricted TranslationIndex [7,297 B]
==> default: Get:42 http://us.archive.ubuntu.com precise-updates/universe TranslationIndex [8,333 B]
==> default: Get:43 http://us.archive.ubuntu.com precise-backports/main Sources [5,411 B]
==> default: Get:44 http://us.archive.ubuntu.com precise-backports/restricted Sources [28 B]
==> default: Get:45 http://us.archive.ubuntu.com precise-backports/universe Sources [42.8 kB]
==> default: Get:46 http://us.archive.ubuntu.com precise-backports/multiverse Sources [5,750 B]
==> default: Get:47 http://us.archive.ubuntu.com precise-backports/main amd64 Packages [5,491 B]
==> default: Get:48 http://us.archive.ubuntu.com precise-backports/restricted amd64 Packages [28 B]
==> default: Get:49 http://us.archive.ubuntu.com precise-backports/universe amd64 Packages [44.2 kB]
==> default: Get:50 http://us.archive.ubuntu.com precise-backports/multiverse amd64 Packages [5,419 B]
==> default: Get:51 http://us.archive.ubuntu.com precise-backports/main i386 Packages [5,484 B]
==> default: Get:52 http://us.archive.ubuntu.com precise-backports/restricted i386 Packages [28 B]
==> default: Get:53 http://us.archive.ubuntu.com precise-backports/universe i386 Packages [44.0 kB]
==> default: Get:54 http://us.archive.ubuntu.com precise-backports/multiverse i386 Packages [5,413 B]
==> default: Get:55 http://us.archive.ubuntu.com precise-backports/main TranslationIndex [202 B]
==> default: Get:56 http://us.archive.ubuntu.com precise-backports/multiverse TranslationIndex [202 B]
==> default: Get:57 http://us.archive.ubuntu.com precise-backports/restricted TranslationIndex [193 B]
==> default: Get:58 http://us.archive.ubuntu.com precise-backports/universe TranslationIndex [205 B]
==> default: Hit http://us.archive.ubuntu.com precise/main Translation-en
==> default: Hit http://us.archive.ubuntu.com precise/multiverse Translation-en
==> default: Hit http://us.archive.ubuntu.com precise/restricted Translation-en
==> default: Hit http://us.archive.ubuntu.com precise/universe Translation-en
==> default: Get:59 http://us.archive.ubuntu.com precise-updates/main Translation-en [405 kB]
==> default: Get:60 http://us.archive.ubuntu.com precise-updates/multiverse Translation-en [9,603 B]
==> default: Get:61 http://us.archive.ubuntu.com precise-updates/restricted Translation-en [2,982 B]
==> default: Get:62 http://us.archive.ubuntu.com precise-updates/universe Translation-en [160 kB]
==> default: Get:63 http://us.archive.ubuntu.com precise-backports/main Translation-en [4,911 B]
==> default: Get:64 http://us.archive.ubuntu.com precise-backports/multiverse Translation-en [4,838 B]
==> default: Hit http://us.archive.ubuntu.com precise-backports/restricted Translation-en
==> default: Get:65 http://us.archive.ubuntu.com precise-backports/universe Translation-en [35.0 kB]
==> default: Fetched 6,209 kB in 11s (538 kB/s)
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   g++-4.6 git-man liberror-perl libstdc++6-4.6-dev patch python-minimal
==> default:   python-pycurl unattended-upgrades
==> default: Suggested packages:
==> default:   g++-multilib g++-4.6-multilib gcc-4.6-doc libstdc++6-4.6-dbg git-daemon-run
==> default:   git-daemon-sysvinit git-doc git-el git-arch git-cvs git-svn git-email
==> default:   git-gui gitk gitweb libstdc++6-4.6-doc make-doc diffutils-doc python-doc
==> default:   python-tk libcurl4-gnutls-dev python-pycurl-dbg bsd-mailx
==> default: The following NEW packages will be installed:
==> default:   g++ g++-4.6 git git-man liberror-perl libstdc++6-4.6-dev make patch
==> default:   python-pycurl python-software-properties unattended-upgrades
==> default: The following packages will be upgraded:
==> default:   python python-minimal
==> default: 2 upgraded, 11 newly installed, 0 to remove and 181 not upgraded.
==> default: Need to get 15.9 MB of archives.
==> default: After this operation, 41.8 MB of additional disk space will be used.
==> default: Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main python-minimal amd64 2.7.3-0ubuntu2.2 [29.7 kB]
==> default: Get:2 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main python amd64 2.7.3-0ubuntu2.2 [168 kB]
==> default: Get:3 http://us.archive.ubuntu.com/ubuntu/ precise/main libstdc++6-4.6-dev amd64 4.6.3-1ubuntu5 [1,660 kB]
==> default: Get:4 http://us.archive.ubuntu.com/ubuntu/ precise/main g++-4.6 amd64 4.6.3-1ubuntu5 [6,954 kB]
==> default: Get:5 http://us.archive.ubuntu.com/ubuntu/ precise/main g++ amd64 4:4.6.3-1ubuntu5 [1,442 B]
==> default: Get:6 http://us.archive.ubuntu.com/ubuntu/ precise/main liberror-perl all 0.17-1 [23.8 kB]
==> default: Get:7 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main git-man all 1:1.7.9.5-1ubuntu0.1 [631 kB]
==> default: Get:8 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main git amd64 1:1.7.9.5-1ubuntu0.1 [6,097 kB]
==> default: Get:9 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main make amd64 3.81-8.1ubuntu1.1 [119 kB]
==> default: Get:10 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main patch amd64 2.6.1-3ubuntu0.1 [80.0 kB]
==> default: Get:11 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main unattended-upgrades all 0.76ubuntu1.1 [24.7 kB]
==> default: Get:12 http://us.archive.ubuntu.com/ubuntu/ precise/main python-pycurl amd64 7.19.0-4ubuntu3 [49.2 kB]
==> default: Get:13 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main python-software-properties all 0.82.7.7 [23.5 kB]
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Fetched 15.9 MB in 34s (465 kB/s)
==> default: (Reading database ... 
==> default: 51095 files and directories currently installed.)
==> default: Preparing to replace python-minimal 2.7.3-0ubuntu2 (using .../python-minimal_2.7.3-0ubuntu2.2_amd64.deb) ...
==> default: Unpacking replacement python-minimal ...
==> default: Processing triggers for man-db ...
==> default: Setting up python-minimal (2.7.3-0ubuntu2.2) ...
==> default: (Reading database ... 
==> default: 51095 files and directories currently installed.)
==> default: Preparing to replace python 2.7.3-0ubuntu2 (using .../python_2.7.3-0ubuntu2.2_amd64.deb) ...
==> default: Unpacking replacement python ...
==> default: Selecting previously unselected package libstdc++6-4.6-dev.
==> default: Unpacking libstdc++6-4.6-dev (from .../libstdc++6-4.6-dev_4.6.3-1ubuntu5_amd64.deb) ...
==> default: Selecting previously unselected package g++-4.6.
==> default: Unpacking g++-4.6 (from .../g++-4.6_4.6.3-1ubuntu5_amd64.deb) ...
==> default: Selecting previously unselected package g++.
==> default: Unpacking g++ (from .../g++_4%3a4.6.3-1ubuntu5_amd64.deb) ...
==> default: Selecting previously unselected package liberror-perl.
==> default: Unpacking liberror-perl (from .../liberror-perl_0.17-1_all.deb) ...
==> default: Selecting previously unselected package git-man.
==> default: Unpacking git-man (from .../git-man_1%3a1.7.9.5-1ubuntu0.1_all.deb) ...
==> default: Selecting previously unselected package git.
==> default: Unpacking git (from .../git_1%3a1.7.9.5-1ubuntu0.1_amd64.deb) ...
==> default: Selecting previously unselected package make.
==> default: Unpacking make (from .../make_3.81-8.1ubuntu1.1_amd64.deb) ...
==> default: Selecting previously unselected package patch.
==> default: Unpacking patch (from .../patch_2.6.1-3ubuntu0.1_amd64.deb) ...
==> default: Selecting previously unselected package unattended-upgrades.
==> default: Unpacking unattended-upgrades (from .../unattended-upgrades_0.76ubuntu1.1_all.deb) ...
==> default: Selecting previously unselected package python-pycurl.
==> default: Unpacking python-pycurl (from .../python-pycurl_7.19.0-4ubuntu3_amd64.deb) ...
==> default: Selecting previously unselected package python-software-properties.
==> default: Unpacking python-software-properties (from .../python-software-properties_0.82.7.7_all.deb) ...
==> default: Processing triggers for man-db ...
==> default: Processing triggers for ureadahead ...
==> default: ureadahead will be reprofiled on next reboot
==> default: Setting up python (2.7.3-0ubuntu2.2) ...
==> default: Setting up liberror-perl (0.17-1) ...
==> default: Setting up git-man (1:1.7.9.5-1ubuntu0.1) ...
==> default: Setting up git (1:1.7.9.5-1ubuntu0.1) ...
==> default: Setting up make (3.81-8.1ubuntu1.1) ...
==> default: Setting up patch (2.6.1-3ubuntu0.1) ...
==> default: Setting up unattended-upgrades (0.76ubuntu1.1) ...
==> default: Setting up python-pycurl (7.19.0-4ubuntu3) ...
==> default: Setting up python-software-properties (0.82.7.7) ...
==> default: Setting up g++-4.6 (4.6.3-1ubuntu5) ...
==> default: Setting up g++ (4:4.6.3-1ubuntu5) ...
==> default: update-alternatives: 
==> default: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode.
==> default: Setting up libstdc++6-4.6-dev (4.6.3-1ubuntu5) ...
==> default: gpg: 
==> default: keyring `/tmp/tmp54xj3n/secring.gpg' created
==> default: gpg: 
==> default: keyring `/tmp/tmp54xj3n/pubring.gpg' created
==> default: gpg: 
==> default: requesting key C7917B12 from hkp server keyserver.ubuntu.com
==> default: gpg: 
==> default: /tmp/tmp54xj3n/trustdb.gpg: trustdb created
==> default: gpg: 
==> default: key C7917B12: public key "Launchpad chrislea" imported
==> default: gpg: 
==> default: Total number processed: 1
==> default: gpg: 
==> default:               imported: 1
==> default:   (RSA: 1)
==> default: OK
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Ign http://ppa.launchpad.net precise InRelease
==> default: Ign http://security.ubuntu.com precise-security InRelease
==> default: Get:1 http://ppa.launchpad.net precise Release.gpg [316 B]
==> default: Hit http://security.ubuntu.com precise-security Release.gpg
==> default: Get:2 http://ppa.launchpad.net precise Release [12.9 kB]
==> default: Hit http://security.ubuntu.com precise-security Release
==> default: Get:3 http://ppa.launchpad.net precise/main Sources [830 B]
==> default: Hit http://security.ubuntu.com precise-security/main Sources
==> default: Get:4 http://ppa.launchpad.net precise/main amd64 Packages [970 B]
==> default: Get:5 http://ppa.launchpad.net precise/main i386 Packages [968 B]
==> default: Get:6 http://ppa.launchpad.net precise/main TranslationIndex [199 B]
==> default: Hit http://security.ubuntu.com precise-security/restricted Sources
==> default: Hit http://security.ubuntu.com precise-security/universe Sources
==> default: Hit http://security.ubuntu.com precise-security/multiverse Sources
==> default: Hit http://security.ubuntu.com precise-security/main amd64 Packages
==> default: Hit http://security.ubuntu.com precise-security/restricted amd64 Packages
==> default: Get:7 http://ppa.launchpad.net precise/main Translation-en [727 B]
==> default: Hit http://security.ubuntu.com precise-security/universe amd64 Packages
==> default: Hit http://security.ubuntu.com precise-security/multiverse amd64 Packages
==> default: Hit http://security.ubuntu.com precise-security/main i386 Packages
==> default: Hit http://security.ubuntu.com precise-security/restricted i386 Packages
==> default: Hit http://security.ubuntu.com precise-security/universe i386 Packages
==> default: Hit http://security.ubuntu.com precise-security/multiverse i386 Packages
==> default: Hit http://security.ubuntu.com precise-security/main TranslationIndex
==> default: Hit http://security.ubuntu.com precise-security/multiverse TranslationIndex
==> default: Hit http://security.ubuntu.com precise-security/restricted TranslationIndex
==> default: Hit http://security.ubuntu.com precise-security/universe TranslationIndex
==> default: Hit http://security.ubuntu.com precise-security/main Translation-en
==> default: Hit http://security.ubuntu.com precise-security/multiverse Translation-en
==> default: Hit http://security.ubuntu.com precise-security/restricted Translation-en
==> default: Hit http://security.ubuntu.com precise-security/universe Translation-en
==> default: Ign http://us.archive.ubuntu.com precise InRelease
==> default: Ign http://us.archive.ubuntu.com precise-updates InRelease
==> default: Ign http://us.archive.ubuntu.com precise-backports InRelease
==> default: Hit http://us.archive.ubuntu.com precise Release.gpg
==> default: Hit http://us.archive.ubuntu.com precise-updates Release.gpg
==> default: Hit http://us.archive.ubuntu.com precise-backports Release.gpg
==> default: Hit http://us.archive.ubuntu.com precise Release
==> default: Hit http://us.archive.ubuntu.com precise-updates Release
==> default: Hit http://us.archive.ubuntu.com precise-backports Release
==> default: Hit http://us.archive.ubuntu.com precise/main Sources
==> default: Hit http://us.archive.ubuntu.com precise/restricted Sources
==> default: Hit http://us.archive.ubuntu.com precise/universe Sources
==> default: Hit http://us.archive.ubuntu.com precise/multiverse Sources
==> default: Hit http://us.archive.ubuntu.com precise/main amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise/restricted amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise/universe amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise/multiverse amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise/main i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise/restricted i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise/universe i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise/multiverse i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise/main TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise/multiverse TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise/restricted TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise/universe TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise-updates/main Sources
==> default: Hit http://us.archive.ubuntu.com precise-updates/restricted Sources
==> default: Hit http://us.archive.ubuntu.com precise-updates/universe Sources
==> default: Hit http://us.archive.ubuntu.com precise-updates/multiverse Sources
==> default: Hit http://us.archive.ubuntu.com precise-updates/main amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise-updates/restricted amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise-updates/universe amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise-updates/multiverse amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise-updates/main i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise-updates/restricted i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise-updates/universe i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise-updates/multiverse i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise-updates/main TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise-updates/multiverse TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise-updates/restricted TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise-updates/universe TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise-backports/main Sources
==> default: Hit http://us.archive.ubuntu.com precise-backports/restricted Sources
==> default: Hit http://us.archive.ubuntu.com precise-backports/universe Sources
==> default: Hit http://us.archive.ubuntu.com precise-backports/multiverse Sources
==> default: Hit http://us.archive.ubuntu.com precise-backports/main amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise-backports/restricted amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise-backports/universe amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise-backports/multiverse amd64 Packages
==> default: Hit http://us.archive.ubuntu.com precise-backports/main i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise-backports/restricted i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise-backports/universe i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise-backports/multiverse i386 Packages
==> default: Hit http://us.archive.ubuntu.com precise-backports/main TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise-backports/multiverse TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise-backports/restricted TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise-backports/universe TranslationIndex
==> default: Hit http://us.archive.ubuntu.com precise/main Translation-en
==> default: Hit http://us.archive.ubuntu.com precise/multiverse Translation-en
==> default: Hit http://us.archive.ubuntu.com precise/restricted Translation-en
==> default: Hit http://us.archive.ubuntu.com precise/universe Translation-en
==> default: Hit http://us.archive.ubuntu.com precise-updates/main Translation-en
==> default: Hit http://us.archive.ubuntu.com precise-updates/multiverse Translation-en
==> default: Hit http://us.archive.ubuntu.com precise-updates/restricted Translation-en
==> default: Hit http://us.archive.ubuntu.com precise-updates/universe Translation-en
==> default: Hit http://us.archive.ubuntu.com precise-backports/main Translation-en
==> default: Hit http://us.archive.ubuntu.com precise-backports/multiverse Translation-en
==> default: Hit http://us.archive.ubuntu.com precise-backports/restricted Translation-en
==> default: Hit http://us.archive.ubuntu.com precise-backports/universe Translation-en
==> default: Fetched 16.9 kB in 1s (10.8 kB/s)
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   rlwrap
==> default: The following NEW packages will be installed:
==> default:   nodejs rlwrap
==> default: 0 upgraded, 2 newly installed, 0 to remove and 181 not upgraded.
==> default: Need to get 6,100 kB of archives.
==> default: After this operation, 18.6 MB of additional disk space will be used.
==> default: Get:1 http://ppa.launchpad.net/chris-lea/node.js/ubuntu/ precise/main nodejs amd64 0.10.37-1chl1~precise1 [6,019 kB]
==> default: Get:2 http://us.archive.ubuntu.com/ubuntu/ precise/universe rlwrap amd64 0.37-2 [81.0 kB]
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Fetched 6,100 kB in 2s (2,260 kB/s)
==> default: Selecting previously unselected package rlwrap.
==> default: (Reading database ... 
==> default: 52600 files and directories currently installed.)
==> default: Unpacking rlwrap (from .../rlwrap_0.37-2_amd64.deb) ...
==> default: Selecting previously unselected package nodejs.
==> default: Unpacking nodejs (from .../nodejs_0.10.37-1chl1~precise1_amd64.deb) ...
==> default: Processing triggers for man-db ...
==> default: Setting up rlwrap (0.37-2) ...
==> default: update-alternatives: 
==> default: using /usr/bin/rlwrap to provide /usr/bin/readline-editor (readline-editor) in auto mode.
==> default: Setting up nodejs (0.10.37-1chl1~precise1) ...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: /usr/bin/_mocha -> /usr/lib/node_modules/mocha/bin/_mocha
==> default: /usr/bin/mocha -> /usr/lib/node_modules/mocha/bin/mocha
==> default: 
==> default: > nodegit@0.4.1 install /usr/lib/node_modules/nodegit
==> default: > node lifecycleScripts/install
==> default: [nodegit] Fetching binary from S3.
==> default: [nodegit] Failed to install prebuilt binary, building manually.
==> default: [nodegit] Making sure dependencies are available and native code is generated
==> default: [nodegit] Everything is ready to go, attempting compilation
==> default: [nodegit] Building native node module.
==> default: { [Error: Command failed: npm ERR! addLocal Could not install /usr/lib/node_modules/nodegit
==> default: npm ERR! Linux 3.2.0-23-generic
==> default: npm ERR! argv "node" "/usr/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
==> default: npm ERR! node v0.10.37
==> default: npm ERR! npm  v2.14.5
==> default: npm ERR! path /root/.npm/nodegit/0.4.1/package
==> default: npm ERR! code EACCES
==> default: npm ERR! errno 3
==> default: 
==> default: npm ERR! Error: EACCES, mkdir '/root/.npm/nodegit/0.4.1/package'
==> default: npm ERR!  { [Error: EACCES, mkdir '/root/.npm/nodegit/0.4.1/package']
==> default: npm ERR!   errno: 3,
==> default: npm ERR!   code: 'EACCES',
==> default: npm ERR!   path: '/root/.npm/nodegit/0.4.1/package' }
==> default: npm ERR! 
==> default: npm ERR! Please try running this command again as root/Administrator.
==> default: 
==> default: npm ERR! Please include the following file with any support request:
==> default: npm ERR!     /usr/lib/node_modules/nodegit/npm-debug.log
==> default: ] killed: false, code: 3, signal: null }
==> default: undefined
==> default: mocha@2.3.3 /usr/lib/node_modules/mocha
==> default: ├── escape-string-regexp@1.0.2
==> default: ├── supports-color@1.2.0
==> default: ├── growl@1.8.1
==> default: ├── commander@2.3.0
==> default: ├── diff@1.4.0
==> default: ├── debug@2.0.0 (ms@0.6.2)
==> default: ├── mkdirp@0.5.0 (minimist@0.0.8)
==> default: ├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
==> default: └── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
==> default: 
==> default: nodegit@0.4.1 /usr/lib/node_modules/nodegit
==> default: ├── nodegit-promise@2.0.1 (asap@2.0.3)
==> default: ├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
==> default: ├── which-native-nodish@1.1.3 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
==> default: ├── fs-extra@0.18.4 (jsonfile@2.2.2, graceful-fs@3.0.8, rimraf@2.4.3)
==> default: └── npm@2.14.5
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: 
==> default: > nodegit@0.4.1 install /usr/lib/node_modules/git-hours/node_modules/nodegit
==> default: > node lifecycleScripts/install
==> default: [nodegit] Fetching binary from S3.
==> default: [nodegit] Failed to install prebuilt binary, building manually.
==> default: [nodegit] Making sure dependencies are available and native code is generated
==> default: [nodegit] Everything is ready to go, attempting compilation
==> default: [nodegit] Building native node module.
==> default: { [Error: Command failed: npm ERR! tar.pack Could not write /home/vagrant/.npm/nodegit/0.4.1/package.tgz
==> default: npm ERR! addLocalDirectory Could not pack /usr/lib/node_modules/git-hours/node_modules/nodegit to /home/vagrant/.npm/nodegit/0.4.1/package.tgz
==> default: npm ERR! addLocal Could not install /usr/lib/node_modules/git-hours/node_modules/nodegit
==> default: npm ERR! Linux 3.2.0-23-generic
==> default: npm ERR! argv "node" "/usr/lib/node_modules/git-hours/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
==> default: npm ERR! node v0.10.37
==> default: npm ERR! npm  v2.14.5
==> default: npm ERR! path /home/vagrant/.npm/nodegit/0.4.1/package.tgz.2974a6d18ef76bbd174c29cda9c35c1a
==> default: npm ERR! code EACCES
==> default: npm ERR! errno 3
==> default: 
==> default: npm ERR! Error: EACCES, open '/home/vagrant/.npm/nodegit/0.4.1/package.tgz.2974a6d18ef76bbd174c29cda9c35c1a'
==> default: npm ERR!  { [Error: EACCES, open '/home/vagrant/.npm/nodegit/0.4.1/package.tgz.2974a6d18ef76bbd174c29cda9c35c1a']
==> default: npm ERR!   errno: 3,
==> default: npm ERR!   code: 'EACCES',
==> default: npm ERR!   path: '/home/vagrant/.npm/nodegit/0.4.1/package.tgz.2974a6d18ef76bbd174c29cda9c35c1a' }
==> default: npm ERR! 
==> default: npm ERR! Please try running this command again as root/Administrator.
==> default: 
==> default: npm ERR! Please include the following file with any support request:
==> default: npm ERR!     /usr/lib/node_modules/git-hours/node_modules/nodegit/npm-debug.log
==> default: ] killed: false, code: 3, signal: null }
==> default: undefined
==> default: /usr/bin/git-hours -> /usr/lib/node_modules/git-hours/src/index.js
==> default: git-hours@1.1.0 /usr/lib/node_modules/git-hours
==> default: ├── bluebird@2.10.1
==> default: ├── lodash@2.4.2
==> default: ├── moment@2.10.6
==> default: ├── commander@2.8.1 (graceful-readlink@1.0.1)
==> default: └── nodegit@0.4.1 (promisify-node@0.1.5, nodegit-promise@2.0.1, which-native-nodish@1.1.3, fs-extra@0.18.4, npm@2.14.5)

**Comment by kimmobrunfeldt** [comment]
What nodejs version are you running locally? Make sure you have 0.12.x version when installing git-hours. 

About the Vagrant: sorry I don't know the details about Vagrant configuration, I accepted the config as a PR. It seems that the user inside vagrant does not have access rights to /root/.npm folder.

**Comment by SwiftPengu** [comment]
My local node version is 4.1.1, so that must be the reason why it's not working locally.
My vagrant vm is a clean one, so any rights problems might be resolved by altering the config file.

**Comment by SwiftPengu** [comment]
I just discovered that running git-hours from an admin console in Windows fixes the nodegit problem.
The vagrant problem remains though.

**Comment by fabiosoft** [comment]
Vagrant issue solved here. #13

**Comment by kimmobrunfeldt** [comment]
Let's continue issue here https://github.com/kimmobrunfeldt/git-hours/issues/15
