### ISSUE TITLE
ruby

### ISSUE THREAD

**Issue by jonasman** [kimmobrunfeldt/git-hours#24]
I had to install loads of software just to run this 30 lines of code! (vagrant, virtualBox, vagrant plugin scp, gitnode) In the end i couldnt run it :D 

As a recommendation next time do it in ruby. Mac os X already suports it!
and ruby gems are the way to go.

**Comment by GuyPaddock** [comment]
@jonasman There's no way you're serious. `npm` and NodeJS is significantly more portable than Ruby. Most Ruby developers will tell you Ruby only runs on Linux and OSX -- if you're on Windows, forget it. There is a Windows version of Ruby, but gems almost never work properly there without help. Even Compass -- originally the de facto compiler for SASS -> CSS -- has been superseded by a NodeJS-based plugin built on `libSass`.

**Comment by jonasman** [comment]
Actually i ignored this lib and went to the source. And used the ruby version :)
