### ISSUE TITLE
Clarifications on differences from Clockout

### ISSUE THREAD

**Issue by adrianmcli** [kimmobrunfeldt/git-hours#27]
@kimmobrunfeldt I saw on the [clockout repo](https://github.com/dingbat/clockout) that you based this tool on that one. I was wondering why you chose not to incorporate "smart" estimation and instead decided to use a simple threshold method.

Also, should we consider adding the `clock out` and `clock in` feature? Or I suppose it might be best to do that in a separate project.

At any rate, I am interested in extending the functionality of these tools so we can have more powerful analysis of our work activity.

**Comment by kimmobrunfeldt** [comment]
This is an old issue, but I'm trying to answer as many as possible to close the hanging ones. I'm not sure what smart estimation means, I couldn't find a mention from the clockout repo. I'm all in for better calculation suggestions!

I would personally leave the clock in/out feature from this repo, but if many people seem to want it, I can definitely accept a PR.
