### ISSUE TITLE
git-hours cannot be launched from npx

### ISSUE THREAD

**Issue by beenotung** [kimmobrunfeldt/git-hours#45]
## Env
| Software | Version |
|-------------|-----------|
| node | v10.16.0 |
| npm | 6.12.0 |
| OS | Archlinux |

## Suggestions
1. As mentioned in the readme, it is tricky to work with nodegit, could we not depends on it? e.g. just via exec `git log` then parse the stdout directly
2. Could we rewrite it to be standlone npm executable? Instead of hooking onto git alias, i.e. `git-hours` instead of `git hours`

**Comment by beenotung** [comment]
found this one works pretty well https://github.com/vmf91/git-time

**Comment by beenotung** [comment]
inspired by your work, I also made one https://github.com/beenotung/git-hour
which distinct each contributors

**Comment by kimmobrunfeldt** [comment]
After new release 1.5.0, `npx git-hours` works again! Tested with node 14, macOS. The node version is probably quite specific.
