### ISSUE TITLE
So, I spent 3 hours trying to vagrant up

### ISSUE THREAD

**Issue by niclowe** [kimmobrunfeldt/git-hours#6]
....then, finally, I install my repo, and type 'git hours' at the prompt expecting magic.
I get this

vagrant@git-hours:~/XXXXXX$ git hours
git: 'hours' is not a git command. See 'git --help'.
vagrant@git-hours:~/XXXXXX$

Any idea at all?

**Comment by kimmobrunfeldt** [comment]
Try to run `git-hours`. To get the `git hours` working, I guess you have to have git-hours command in your $PATH. Anyways, just `git-hours` should work.

**Comment by kimmobrunfeldt** [comment]
I changed the wording about Vagrant in the README.md. It's more about easing the pain to install the dependencies: node, nodegit etc. Not always the quickest installation option.

**Comment by niclowe** [comment]
Nah 'git-hours' didnt work - for me

**Comment by kimmobrunfeldt** [comment]
I just installed the vagrant box with: `vagrant up`, then `vagrant ssh` and `git hours` command worked for me so I can't replicate the issue.
<img width="1016" alt="screenshot 2015-07-24 11 03 25" src="https://cloud.githubusercontent.com/assets/1232405/8870083/be671270-31f3-11e5-8e74-60eca4082148.png">

You need to locate where the git-hours binary was installed and run it from there, or add the containing directory to $PATH.

**Comment by niclowe** [comment]
Is it right that that vagrant box has been up since 2012?
I am 'vagrant reload'ing my box now to see if its made a difference

**Comment by niclowe** [comment]
(thanks for your help)

**Comment by niclowe** [comment]
I am not alone

http://stackoverflow.com/questions/31604512/git-hour-hours-is-not-a-git-command

**Comment by kimmobrunfeldt** [comment]
The vagrant apparently is using pretty old version of Ubuntu. Someone three years ago has packaged the box, that's why it shows the last login then. It hasn't been up for three years, though. No problem.

**Comment by niclowe** [comment]
I am confused - there is a git hours binary somewhere?
I cant see it in the repo.......

**Comment by kimmobrunfeldt** [comment]
By "binary" I mean the index.js. On `npm install`, npm should install the file so that it can be run.

**Comment by kimmobrunfeldt** [comment]
I don't know how to help further since I don't have any logs / information about your system. I got it working by following the Vagrant setup guide. Here's an example from my vagrant box:

```bash
➜  git-hours git:(master) ✗ vagrant ssh
git-Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '14.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Welcome to your Vagrant-built virtual machine.
Last login: Fri Jul 24 08:03:02 2015 from 10.0.2.2
git-hvagrant@git-hours:~$ git-hours
Error: Could not find repository from '.'
vagrant@git-hours:~$ which git-hours
/usr/bin/git-hours
vagrant@git-hours:~$ git clone https://github.com/twbs/bootstrap
Cloning into 'bootstrap'...
remote: Counting objects: 73036, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 73036 (delta 0), reused 0 (delta 0), pack-reused 73033
Receiving objects: 100% (73036/73036), 85.69 MiB | 1.35 MiB/s, done.
Resolving deltas: 100% (44482/44482), done.
vagrant@git-hours:~$ cd bootstrap/
vagrant@git-hours:~/bootstrap$ git hours
git-hours{
  "total": {
    "hours": 7894,
    "commits": 11470
  }
}
vagrant@git-hours:~/bootstrap$ git-hours
{
  "total": {
    "hours": 7894,
    "commits": 11470
  }
}
vagrant@git-hours:~/bootstrap$
```

**Comment by kimmobrunfeldt** [comment]
In your vagrant box, try to run:
```
sudo apt-get -y update
sudo apt-get -y install git python-software-properties python g++ make
sudo add-apt-repository -y ppa:chris-lea/node.js
sudo apt-get -y update
sudo apt-get -y install nodejs

npm install -g git-hours
```

After that, try `git hours` in any repository. 

If it doesn't work, please provide the output of the above commands, and also output of:

```
which node
which git-hours
which npm
node --version
npm --version
```

**Comment by niclowe** [comment]
So after I figured out I needed to 'sudo npm install -g git-hours' I got the following error

vagrant@git-hours:~$ sudo npm install -g git-hours
/
> nodegit@0.4.1 install /usr/lib/node_modules/git-hours/node_modules/nodegit
> node lifecycleScripts/install


module.js:485
    throw err;
          ^
SyntaxError: /usr/lib/node_modules/git-hours/node_modules/nodegit/generate/input/v0.22.2.json: Unexpected token

npm ERR! nodegit@0.4.1 install: `node lifecycleScripts/install`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the nodegit@0.4.1 install script.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "git-hours"
npm ERR! cwd /home/vagrant
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

I will shortly post the responses to your commands

**Comment by niclowe** [comment]
> which node 

usr/bin/node/

> which git-hours

Nothing. Nada. Probably related to failed install above

>which npm

usr/bin/npm

>node --version

v0.10.37

>npm --version

1.4.28

**Comment by niclowe** [comment]
Not sure if this helps, but i rebuilt the vagrant box and I noticed this error


==> default: [nodegit] Everything is ready to go, attempting compilation
==> default: [nodegit] Building native node module.
==> default: { [Error: Command failed: npm ERR! addLocal Could not install /usr/lib/node_modules/nodegit
==> default: npm ERR! Linux 3.2.0-23-generic
==> default: npm ERR! argv "node" "/usr/lib/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
==> default: npm ERR! node v0.10.37
==> default: npm ERR! npm  v2.13.2
==> default: npm ERR! path /root/.npm/nodegit/0.4.1/package
==> default: npm ERR! code EACCES
==> default: npm ERR! errno 3
==> default:
==> default: npm ERR! Error: EACCES, mkdir '/root/.npm/nodegit/0.4.1/package'
==> default: npm ERR!  { [Error: EACCES, mkdir '/root/.npm/nodegit/0.4.1/package']
==> default: npm ERR!   errno: 3,
==> default: npm ERR!   code: 'EACCES',
==> default: npm ERR!   path: '/root/.npm/nodegit/0.4.1/package' }
==> default: npm ERR!
==> default: npm ERR! Please try running this command again as root/Administrator.
==> default:
==> default: npm ERR! Please include the following file with any support request:
==> default: npm ERR!     /usr/lib/node_modules/nodegit/npm-debug.log
==> default: ] killed: false, code: 3, signal: null }
==> default: undefined
==> default: mocha@2.2.5 /usr/lib/node_modules/mocha
==> default: ├── escape-string-regexp@1.0.2
==> default: ├── supports-color@1.2.1
==> default: ├── growl@1.8.1
==> default: ├── commander@2.3.0
==> default: ├── diff@1.4.0
==> default: ├── debug@2.0.0 (ms@0.6.2)
==> default: ├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
==> default: ├── mkdirp@0.5.0 (minimist@0.0.8)
==> default: └── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
==> default:
==> default: nodegit@0.4.1 /usr/lib/node_modules/nodegit
==> default: ├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
==> default: ├── nodegit-promise@2.0.1 (asap@2.0.3)
==> default: ├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
==> default: ├── fs-extra@0.18.4 (jsonfile@2.2.1, graceful-fs@3.0.8, rimraf@2.4.2)
==> default: └── npm@2.13.2
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default:
==> default: > nodegit@0.1.4 install /usr/lib/node_modules/git-hours/node_modules/nodegit
==> default: > node install.js
==> default: [nodegit] Determining dependencies.
==> default: [nodegit] Removing vendor/libgit2.
==> default: [nodegit] Fetching vendor/libgit2.
==> default: [nodegit] Configuring native node module.
==> default: [nodegit] Building native node module.
==> default: [nodegit] Failed to build nodegit.
==> default: [nodegit] Attempting to fallback on a prebuilt binary.
==> default: [nodegit] Fetching binary from S3.
==> default: [nodegit] Completed installation successfully.
==> default: /usr/bin/git-hours -> /usr/lib/node_modules/git-hours/index.js
==> default: git-hours@0.2.0 /usr/lib/node_modules/git-hours
==> default: ├── bluebird@2.9.34
==> default: ├── lodash@2.4.2
==> default: ├── commander@2.8.1 (graceful-readlink@1.0.1)
==> default: ├── mocha@1.21.5 (escape-string-regexp@1.0.2, diff@1.0.8, growl@1.8.1, commander@2.3.0, debug@2.0.0, jade@0.26.3, mkdirp@0.5.0, glob@3.2.3)
==> default: └── nodegit@0.1.4 (which@1.0.9, rimraf@2.2.8, q@1.0.1, nan@1.2.0, fs-extra@0.9.1, tar@0.1.20, node-gyp@0.13.1, request@2.36.0)

**Comment by niclowe** [comment]
Kimmo, Im sorry, I gave up.....

**Comment by kimmobrunfeldt** [comment]
@niclowe I got that same error when installing vagrant box but git-hours worked in the end. I'm sorry that you didn't get this fun tool running, nodegit is indeed quite tough to get installed sometimes.

Since you gave up I'll close this for now. Feel free to reopen this issue if you want to get back to this. We can have a Google Hangouts if you want to get it working. Anyone else getting the same error, please reopen this issue.

**Comment by PhilAlton** [comment]
Had the same problem, and have found a work around:
Install nodegit manually (run npm install -g nodegit [as an administrator / i.e. sudo or cmd with admin privileges])
Locate the node_modules root directory (should now include both nodegit and git-hours). Navigate into nodegit's build folder and copy the release folder. Now navigate to the node_modules/git-hours folder, and then to git-hour's node_modules folder (which will contain a nodegit folder). Replace the git-hours\node_modules\nodegit\build\Release folder with the Release folder from node_modules\nodegit\build\Release. Furthermore, copy the folder again to the same directory, but this time name it Debug, not Release.
3). Try running git hours again, from within your chosen git repo.

**Comment by miguno** [comment]
For others reading this: I found a working solution (May 2025) by using a Rust rewrite of git-hours. See https://github.com/kimmobrunfeldt/git-hours/issues/79#issuecomment-2900754014. Hope this helps.
